# Generated by Django 4.0.2 on 2022-06-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='portfolio',
            field=models.JSONField(default='{}'),
        ),
    ]
