# Generated by Django 4.0.2 on 2022-06-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_team_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_balance',
            field=models.FloatField(default=100000),
        ),
    ]
