# Generated by Django 4.0.2 on 2022-06-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_team_team_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='portfolio_short',
            field=models.JSONField(default='{}'),
        ),
    ]
